services:


  db_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    hostname: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mydatabase  # This creates the 'mydatabase' database
    hostname: db_host
    ports:
      - 5432:5432
